const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST";
const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
const FETCH_CONTACTS_ERROR = "FETCH_CONTACTS_ERROR";

export { FETCH_CONTACTS_REQUEST, FETCH_CONTACTS_SUCCESS, FETCH_CONTACTS_ERROR };